name: Syntax Tree Debug

on:
  push:
    branches:
      - test/marketplace-mobile-system-regressions

jobs:
  format:
    runs-on: ubuntu-latest
    container: discourse/discourse_test:slim
    steps:
      - uses: actions/checkout@v6
      - run: bundle install
      - name: Print formatted mobile spec
        run: bundle exec stree format spec/system/marketplace_mobile_layout_spec.rb
